<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class StokmasukModel extends CI_Model
{

    public $table = 'stokmasuk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    public function cariProduk($nama){
        $this->db->like('nama', $nama , 'both');
        $this->db->order_by('nama', 'ASC');
        $this->db->limit(10);
        return $this->db->get('stok')->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->or_like('id_suplier', $q);
    	$this->db->or_like('nama_produk', $q);
    	$this->db->or_like('id_produk', $q);
    	$this->db->or_like('tanggal', $q);
    	$this->db->or_like('jumlah', $q);
    	$this->db->or_like('modal', $q);
        $this->db->or_like('jual', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->or_like('id_suplier', $q);
    	$this->db->or_like('nama_produk', $q);
    	$this->db->or_like('id_produk', $q);
    	$this->db->or_like('tanggal', $q);
    	$this->db->or_like('jumlah', $q);
    	$this->db->or_like('modal', $q);
        $this->db->or_like('jual', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function update_stok($id, $stok, $modal, $jual) {
        $this->db->set('stok', $stok, FALSE);
        $this->db->set('modal', $modal, FALSE);
        $this->db->set('jual', $jual, FALSE);
        $this->db->where('id', $id);
        $this->db->update('stok');
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function insert_mass($data) {
        $this->db->insert_batch($this->table, $data);
    }

    function update_stok_mass($data_update) {
        $this->db->update_batch('stok', $data_update, 'id');
    }
}

/* End of file StokmasukModel.php */
/* Location: ./application/models/StokmasukModel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-20 07:23:24 */
/* http://harviacode.com */